services:
  postgres:
    image: postgres:15
    container_name: netflixir_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: netflixir_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: netflixir_app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "ecto://postgres:postgres@postgres:5432/netflixir_dev"
      MIX_ENV: dev
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    command: mix phx.server

volumes:
  postgres_data:
